services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "5000:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=user
      - POSTGRES_DB=products-api
volumes:
  db_data: