version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "5000:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=user
      - POSTGRES_DB=root
